language: python
sudo: required
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip3 install --upgrade pip pipenv
install:
  - pipenv install
  - pipenv install --dev
script:
  - tox

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
  - stage: deploy
    python: 3.6
    install: true
    script: true
    after_success: true
    deploy:
      provider: pypi
      user: cccaballero
      password:
        secure: "gqe3V/aZFJlRqj4+g2Sy82yDfcaAvH3rpLUgjTr+3Fe5Ab9vgDSfHHE1an+G919s5vaWA+gM9m82EUjnZV+G+7oSp5S2h0elyIqXk6IIOiXThsGZsYCvBeC1LXcFjCK7brOCNVoX5TcbzoSf9qiWCczmOEW25oTJaOetOq35XzG1xtczo4DS7wIcnhpbVrpoCIl9BedW0Xcl5VrBBpjYaBQ20bK2dw8mojhDe9mA+4d+5aB+V996ki8Ll/HVHINVA/PS6Ft1IrMol5cuMc9Kx1SvQ3O2eJPz6qMX5loUWMzz7ookd+Le4mRV5l2/MJBXKEYK5HLSW9R+OXOcrGFIH2EKOcg68oqlCYC/noJ7GipNpe+ItjH+6Y4XbO1/5niyBR1rDmd++b6yQdmuxzHOR7bBfWHSNH207TUaS9dK7QMX9ZF5OgL4TXu+uYrPAtuTmEqfR3/DAmstqAYQoNhd2alZfGOn/CnuW+qGyHo/YuE1SDV+By57TS4A3es4ZKIgpdz/Zz2lxjrAftuqrLSWxwt9HOaEF+vlxMCMvQ5DBpJK3uwvkz1s1xuEY0/PWrvUzDVql5VODClzHtNTkodrZGiuDKwmmm8ulVhzBSuvQS4u1n1VnwFA/bhMFJSlWAb+Z5kZfxtu47itdVrLL+G1oZMWmj/OnhCbk8HtoyDlI4Y="
      on:
        all_branches: true
