language: python
sudo: required
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip3 install --upgrade pip pipenv
install:
  - pipenv install
  - pipenv install --dev
script:
  - tox

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
  - stage: deploy
    python: 3.6
    install: true
    script: true
    after_success: true
    deploy:
      provider: pypi
      user: cccaballero
      password:
        secure: "jNTG8vQOV2qFvvwP4Br0ZbdA5AYrUrxPeqPbwBYYbREEpljKG+75ka/9kXu3D22qGPpWh/Weer17XN6kxG5H0FqjqBKtL4+F+BkPPGmbKqAH4lTsaQndEx5lLmcjNMIqzIIMoIWz/cvU1gVQ4ZOdw5EdhogZukOaoHrSdmSA1VBqa/77KpH4/WV6E3Mb0a+yOkf4OEPZt94IXm1FRQaHpHPpTt5OED2xMTNptDkxmea9jcT5eJIry1EB5i3sSY6c81qxmMbf1PHAT5uos47k/LAcbN7rJD56730eaRubnwbrpIfDVqYfwIfTFlmolaiSXMNAcj41a9l0sdicAommpi4+DxI+Un0S40n+lUulCUVwRQqeOLAc8TiMzYrH/2oV9/UQh6y2TUqjL7dGriRSPpeU22fdpu0I8kwPlm998fmDVjSJncvM+prsLmfHANufmqvk1ZQwcdCDoC/nr6ua3b0GhgVh4WI1fmRNcpLlHvWkgp9/hXuQaiQ3UXw1mc8U3AL8iPDHqkxSfdB9AtiGJsv+NKyhV2myiOEOgO6xXMeKkOR8App0DGpa3BLC96IJvCO4A8/JgpYbXSQJBg9xABhNcZVcoGf8fWFyr+LDkY/wFatMW73pW5apEHCGB++8IHjjhP0ViJcf8ycwyiR8xLmip7uLbR3/9+xRBU4aK0A="
      on:
        all_branches: true
