language: python
sudo: required
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip3 install --upgrade pip pipenv
install:
  - pipenv install
  - pipenv install --dev
script:
  - tox

stages:
  - test
  - name: deploy
    if: tag IS present

deploy:
  provider: pypi
  user: cccaballero
  password:
    secure: a0ar26cZtdPM9OWY8EbQTRFlMPGOYhjyLfRYeJyJoIvL+NKQxrlciARrOb9QviHsmRAvQJy8IUshzoSIHvAueKKmGbWKe2eTMsNeOdTp6YI43/NnjRh2+lPw5RTIP45bARabki30LvDyw0K3/Sb8qjzzmGlb4ZZVzQrERJlzHtPjXHQkNZmGnesM84oZoQU7i5I8+DcIVy2raHvU+Kd8zKZOU96+InqRuNh0sjfeOfM3U5OMR04F7eTZBMqExOrQoZBcp+uDc4SBMZB4KNZSndLMtF6Q7BOA5dVOjKv50Ma42T4hIzmfknJLTn4XPsQh0WBCgLJJJx8wqBsqlS+9v3kNw5aHHYsjQ6om5pmroPI8Rbh2lrjLFcASJ+KTD25OxeoMEvgHeGhv1yftXHJRbjh14A69ueoQ0oP4zfrmbrThW6xGIL9LbNBBbqZGtyvO3yNSvTuzX1C27PlGAsO8AMg6Aup0ytlJdwU8NWdPxMSIGj8RdY/nj9tMpU9H8OS/vS0GoMDsUHKOziwJNNHsHCpA2C5FtQtoLmOQRBWDfeifJVTW1OT/4loZ7uEr49n+Z7sixSkgm3zZtlsjpIRZ+BGdh8pL6WzJ5diZPH2aOAOrNkss0YdXUem0bAkdTKiOhNGokKt9LDlZ4Pe7eFx69mTldcjFLVLeOIIO+ceOuN4=
  on:
    tags: true
    all_branches: true
